### PR TITLE
Fix issue copying properties from Event objects

### LINKED ISSUE #55: Transpiled Event Serialization Issue
The `serializeEventDetails` function attempts to perform destructuring assignment on event objects:
https://github.com/unabridged/motion/blob/7464c9955d803af1dbb9062dc71028704d93b335/javascript/serializeEvent.js#L28

However, object destructuring ends up using `hasOwnProperty` when transpiled, as can be seen here:
```js
function serializeEventDetails(event) {
  var details = {};

  var _iterator = _createForOfIteratorHelper(detailProperties),
      _step;

  try {
    for (_iterator.s(); !(_step = _iterator.n()).done;) {
      var property = _step.value;

      if (Object.prototype.hasOwnProperty.call(event, property)) {
        details[property] = event[property];
      }
    }
  } catch (err) {
    _iterator.e(err);
  } finally {
    _iterator.f();
  }

  return details;
}
```

This is an issue since `hasOwnProperty` will always return `false` on Event objects.
[See this StackOverflow for more details](https://stackoverflow.com/questions/31753224/javascript-hasownproperty-always-false-on-event-objects)
```js
const { key } = new KeyboardEvent('keydown', { key: 'test' })
key
// => 'test'

new KeyboardEvent('keydown', { key: 'test' }).hasOwnProperty('key')
// => false
```

_I came across this while using keyboard events, it is not limited to only keyboard events._

### PR DESCRIPTION
**Pull request by latortuga**
Fixes #55

Destructuring assignment on event objects transpiles to a call to
Object.prototype.hasOwnProperty which is always false for Event objects.
Instead, we can copy the fields directly.

### CODE REVIEW

File: javascript/serializeEvent.js [hunk 1]
```diff
@@ -28,9 +28,7 @@ function serializeEventDetails (event) {
   const details = {}
 
   for (const property of detailProperties) {
-    if (Object.prototype.hasOwnProperty.call(event, property)) {
-      details[property] = event[property]
-    }
+    details[property] = event[property]
```
Comment (alecdotninja) [inline javascript/serializeEvent.js:31]: It might be worth checking if `event[property` is `undefined` here to avoid having an object like `{ a: undefined, b: undefined }` since not every event will have every property.

**Review by alecdotninja — APPROVED** [review]
I would rather check the `undefined` thing, but I don't think it will cause a problem not to do it.

**Comment by latortuga** [comment]
Gonna add some tests for this before merging.

**Comment by latortuga** [comment]
Turns out my Rails 5.1 appraisal was not actually working correctly. So I took the opportunity to fix it up in this branch as well. Not ideal but I'm already neck-deep!
